:toc: macro
toc::[]

:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

= devonfw Release notes 2.3 "Dash"

== Release: improving & strengthening the Platform
 
We are proud to announce the immediate release of *devonfw version 2.3* (code named “_Dash_” during development).  This release comes with a bit of a delay as we decided to wait for the publication of OASP4j 2.5. “Dash” contains a slew of new features but in essence it is already driven by what we expect to be the core focus of 2018: strengthening the platform and improving quality.

After one year and a half of rapid expansion, we expect the next release(s) of the devonfw 2.x series to be fully focused on deepening the platform rather than expanding it. That is to say: we should work on improving existing features rather than adding new ones and strengthen the qualitative aspects of the software development life cycle, i.e. testing, infrastructure (CI, provisioning) etc.

“Dash” already is very much an example of this. This release contains the Allure Test Framework as an incubator. This is an automated testing framework for functional testing of web applications. Another incubator is the devonfw Shop Floor which intended to be a compilation of DevOps experiences from the devonfw perspective. And based on this devonfw has been _OpenShift Primed_ (“certified”) by Red Hat. 

There is a whole range of new features and improvements which can be seen in that light. OASP4j 2.5 changes and improves the package structure of the core Java framework. The My Thai Star sample app has now been fully integrated in the different frameworks and the devonfw Guide has once again been significantly expanded and improved. 

== An industrialized platform for the ADcenter

Although less visible to the overall devonfw community, an important driving force was (meaning that lots of work has been done in the context of) the creation of the ADcenter concept towards the end of 2017. Based on a radical transformation of on/near/offshore software delivery, the focus of the ADcenters is to deliver agile & accelerated “Rightshore” services with an emphasis on:

* Delivering Business Value and optimized User Experience
* Innovative software development with state of the art technology
* Highly automated devops; resulting in lower costs & shorter time-to-market

The first two ADcenters, in Valencia (Spain) and Bangalore (India), are already servicing clients all over Europe - Germany, France, Switzerland  and the Netherlands - while ADcenter aligned production teams are currently working for Capgemini UK as well (through Spain).Through the ADcenter, Capgemini establishes industrialized innovation; designed for & with the user. The availability of platforms for industrialized software delivery like devonfw and the Production Line has allowed us to train and make available over a 150 people in very short time. 

The creation of the ADcenter is such a short time is visible proof that we´re getting closer to a situation where devonfw and Production Line are turning into the default development platform for APPS2, thereby standardizing all aspects of the software development life cycle: from training and design, architecture, devops and development,  all the way up to QA and deployment.  

== Changes and new features

=== devonfw dist 

The *devonfw dist*, or distribution, i.e. the central zip file which contains the main working environment for the devonfw developer, has been significantly enhanced. New features include: 

* Eclipse Oxygen integrated
** CheckStyle Plugin installed and configured
** SonarLint Plugin installed and configured
** Git Plugin installed
** FindBugs replaced by SpotBugs and configured
** Tomcat8 specific Oxygen configuration
** CobiGen Plugin installed
* Other Software
** Cmder integrated (when console.bat launched)
** Visual Studio Code latest version included and pre-configured with https://github.com/devonfw/extension-pack-vscode 
** Ant updated to latest.
** Maven updated to latest.
** Java updated to latest.
** Nodejs LTS updated to latest.
** @angular/cli included.
** Yarn package manager included.
** Python3 integrated
** Spyder3 IDE integrated in python3 installation
** OASP4JS-application-template for Angular5 at workspaces/examples
** Devon4sencha starter templates updated

=== OASP4j 2.5

==== Support for JAX-RS & JAX-WS clients

With the aim to enhance the ease in consuming RESTful and SOAP web services, JAX-RS and JAX-WS clients have been introduced. They enable developers to concisely and efficiently implement portable client-side solutions that leverage existing and well-established client-side HTTP connector implementations. Furthermore, the getting started time for consuming web services has been considerably reduced with the default configuration out-of-the-box which can be tweaked as per individual project requirements. 

See: https://github.com/oasp/oasp4j/issues/358

==== Separate security logs for OASP4J log component

Based on OWASP(Open Web Application Security Project), OASP4J aims to give developers more control and flexibility with the logging of security events and tracking of forensic information. Furthermore, it helps classifying the information in log messages and applying masking when necessary. It provides powerful security features while based on set of logging APIs developers are already familiar with over a decade of their experience with Log4J and its successors. 

See: https://github.com/oasp/oasp4j/issues/569

==== Support for Microservices

Integration of an OASP4J application to a Microservices environment can now be leveraged with this release of OASP4J. Introduction of service clients for RESTful and SOAP web services based on Java EE give developers agility and ease to access microservices in the Devon framework. It significantly cuts down the efforts on part of developers around boilerplate code and stresses more focus on the business code improving overall efficiency and quality of deliverables.

See: https://github.com/oasp/oasp4j/pull/589/commits

=== Cobigen

A new version of Cobigen has been included. New features include: 
 
* Swagger/Yaml Plugin for CobiGen. CobiGen is able to read a swagger definition file that follows the OpenAPI 3.0 spec and generate code. A preliminary release was already included in 2.2.1 but the current version is much more mature and stable. See: https://github.com/devonfw/cobigen/wiki/howto_openapi_generation
* Integration of CobiGen into Maven build process. This already existed but has been improved. It consists mainly of documentation + better log output and bug fixes. See: https://github.com/devonfw/cobigen/wiki/cobigen-maven_configuration
* CobiGen Ionic CRUD App generation based on https://github.com/oasp/oasp4js-ionic-application-template
* Cobigen_Templates project and docs updated
* Bugfixes and Hardening

=== My Thai Star Sample Application

From this release on the My Thai Star application has been fully integrated in the different frameworks in the platform. Further more, a more modularized approach has been followed in the current release of My Thai star application to decouple client from implementation details. Which provides better encapsulation of code and dependency management for API and implementation classes. This has been achieved with creation of a new “API” module that contain interfaces for REST services and corresponding Request/Response objects. With existing “Core” module being dependent on “API” module. To read further you can follow the link https://github.com/oasp/my-thai-star/wiki/java-design#basic-architecture-details 

Furthermore: an email and Twitter micro service were integrated in my-thai-star. This is just for demonstration purposes. A full micro service framework is already part of oasp4j 2.5.0

=== Documentation refactoring

The complete devonfw guide is restructured and refactored. Getting started guides are added for easy start with devonfw.Integration of the new Tutorial with the existing devonfw Guide whereby existing chapters of the previous tutorial were converted to Cookbook chapters. Asciidoctor is used for devonfw guide PDF generation. 
See: https://github.com/devonfw/devonfw-guide/wiki

=== OASP4JS

The following changes have been incorporated in OASP4JS:

* Angular CLI 1.6.0,
* Angular 5.1,
* Angular Material 5 and Covalent 1.0.0 RC1,
* PWA enabled,
* Core and Shared Modules included to follow the recommended Angular projects structure, 
* Yarn and NPM compliant since both lock files are included in order to get a stable installation.

=== Admin interface for oasp4j apps 

The new version includes an Integration of an admin interface for oasp4j apps (Spring Boot). This module is based on CodeCentric´s Spring Boot Admin (https://github.com/codecentric/spring-boot-admin). See: https://github.com/devonfw/devon-guide/wiki/Spring-boot-admin-Integration-with-devon4j

=== Devcon 

A new version of Devcon has been released. Fixes and new features include:

* Renaming of system Commands.
* New menu has been added - “other modules”, if menus are more than 10, other modules will display some menus.
* A progress bar has been added for installing the distribution

=== devonfw Modules

Existing devonfw modules can now be accessed with the help of starters following namespace devonfw-<module_name>-starter. Starters available for modules:

* Reporting module
* WinAuth AD Module
* WinAuth SSO Module
* I18n Module
* Async Module
* Integration Module
* Microservice Module
* Compose for Redis Module 

See: https://github.com/devonfw/devon/wiki#ip-modules 

=== devonfw Shop Floor 

This incubator is intended to be a compilation of DevOps experiences from the devonfw perspective. “How we use our devonfw projects in DevOps environments”. Integration with the Production Line, creation and service integration of a Docker-based CI environment and deploying devonfw applications in an OpenShift Origin cluster using devonfw templates.

See: https://github.com/devonfw/devonfw-shop-floor

=== devonfw-testing 

The Allure Test Framework is an automated testing framework for functional testing of web applications and in coming future native mobile apps, web services and databases. All modules have tangible examples of how to build resilient integration test cases based on delivered functions. 

* Examples available under embedded project “Allure-App-Under-Test” and in project wiki: https://github.com/devonfw/devonfw-testing/wiki 
* How to install: https://github.com/devonfw/devonfw-testing/wiki/How-to-install  
* Release Notes: 
** Core Module – ver.4.12.0.3: 
*** Test report with logs and/or screenshots
*** Test groups/tags
*** Data Driven (inside test case, external file) 
*** Test case parallel execution
*** Run on independent Operating System (Java)
*** Externalize test environment (DEV, QA, PROD)
** UI Selenium module – ver. 3.4.0.3:
*** Malleable resolution ( Remote Web Design, Mobile browsers) 
*** Support for many browsers( Internet Explorer, Edge, Chrome, Firefox, Safari)
*** User friendly actions ( elementCheckBox, elementDropdown, etc. )
*** Ubiquese test execution (locally, against Selenium Grid through Jenkins)
*** Page Object Model architecture
*** Selenium WebDriver library ver. 3.4.0

See:  https://github.com/devonfw/devonfw-testing/wiki

=== DOT.NET Framework incubators

The .NET Core and Xamarin frameworks are still under development by a workgroup from The Netherlands, Spain, Poland, Italy, Norway and Germany. The 1.0 release is expected to be coming soon but the current incubator frameworks are already being used in several engagements.  Some features to highlight are:

* Full .NET implementation with multi-platform support
* Detailed documentation for developers
* Docker ready
* Web API server side template :
** Swagger auto-generation
** JWT security
** Entity Framework Support
** Advanced log features
* Xamarin Templates based on Excalibur framework
* My Thai Star implementation:
** Backend (.NET Core)
** FrontEnd (Xamarin)

=== devonfw has been Primed by Red Hat for OpenShift

OpenShift is a supported distribution of Kubernetes from Red Hat for container-based software deployment and management. It is using Docker containers and DevOps tools for accelerated application development. Using OpenShift allows Capgemini to avoid Cloud Vendor lock-in. OpenShift provides devonfw with a state of the art CI/CD environment (devonfw Shop Floor), providing devonfw with a platform for the whole development life cycle: from development to staging / deploy.

See https://hub.openshift.com/primed/120-capgemini and https://github.com/oasp/s2i

=== Harvested components and modules

The devonfw Harvesting process continues to add valuable components and modules to the devonfw platform. The last months the following elements were contributed: 

==== Service Client support (for Micro service Projects). 

This client is for consuming microservices from other application.This solution is already very flexible and customizable.As of now,this is suitable for small and simple project where two or three microservices are invoked. Donated by Jörg Hohwiller. See: https://github.com/devonfw-forge/devonfw-microservices

==== JHipster devonfw code generation

This component was donated by the ADcenter in Valencia. It was made in order to comply with strong requirements (especially from the French BU) to use jHipster for code generation.

JHipster is a code generator based on Yeoman generators. Its default generator generator-jhipster generates a specific JHipster structure. The purpose of generator-jhipster-DevonModule is to generate the structure and files of a typical OASP4j project. It is therefore equivalent to the standard OASP4j application template based CobiGen code generation.

See: https://github.com/devonfw/devon-guide/wiki/cookbook-devon-jhipster-module 

==== Simple Jenkins task status dashboard

This component has been donated by, has been harvested from system in use by, Capgemini  Valencia. This dashboard, apart from an optional gamification element, allows the display of multiple Jenkins instances. See: https://github.com/oasp/jenkins_view 

=== And lots more, among others:

* OASP4J/devonfw docker based build IN a docker process. See: https://github.com/devonfw/devon-guide/wiki/Dockerfile-for-the-maven-based-spring.io-projects

* CI test boot archetype. This is for unit testing.This will create a sample project and add sample web service to it. A Jenkins job will start oasp4j server and will call web service. See: https://github.com/devonfw/devonfw-shop-floor/tree/master/testing/Oasp4jTestingScripts

* CI test Angular starterTemplate. Testing automation for Angular applications (My Thai Star) in Continuous Integration environments by using Headless browsers and creating Node.js scripts. See: https://github.com/oasp/my-thai-star/blob/develop/angular/package.json#L8-L12 and https://github.com/oasp/my-thai-star/blob/develop/angular/karma.conf.js
