:toc: macro
toc::[]


:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing


= devonfw Release notes 2020.12

== Introduction

We are proud to announce the release of devonfw version 2020.12. 

This release includes lots of addition of new features, updates and bug fixes but it is very important to highlight the following improvements:

== devonfw IDE

The consolidated list of features for this devonfw IDE release is as it follows.

=== 2020.12.001

Update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/pull/495[#495]: Documentation corrections
* https://github.com/devonfw/ide/issues/491[#491]: Consider lombok support
* https://github.com/devonfw/ide/pull/489[#489]: Update node to v12.19.0 and VS Code to 1.50.1
* https://github.com/devonfw/ide/issues/470[#470]: reverse merge of workspace settings not sorting properties anymore
* https://github.com/devonfw/ide/issues/483[#483]: Error during installation when npm is already installed
* https://github.com/devonfw/ide/issues/415[#415]: documentation to customize settings
* https://github.com/devonfw/ide/issues/479[#479]: Error for vscode plugin installation
* https://github.com/devonfw/ide/issues/471[#471]: Preconfigure Project Explorer with Hierarchical Project Presentation

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/16?closed=1[milestone 2020.12.001].

=== 2020.08.001

Update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/pull/454[#454]: update to eclipse 2020.06
* https://github.com/devonfw/ide/pull/442[#442]: update nodejs and vscode
* https://github.com/devonfw/ide/issues/432[#432]: vsCode settings are not updated
* https://github.com/devonfw/ide/issues/446[#446]: intellij: doConfigureEclipse: command not found
* https://github.com/devonfw/ide/issues/440[#440]: Software update may lead to inconsistent state due to windows file locks
* https://github.com/devonfw/ide/issues/427[#427]: release: keep leading zeros
* https://github.com/devonfw/ide/issues/450[#450]: update settings
* https://github.com/devonfw/ide/issues/431[#431]: devon build command not working correct for yarn or npm
* https://github.com/devonfw/ide/issues/449[#449]: update to devon4j 2020.08.001

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/12?closed=1[milestone 2020.08.001].

=== 2020.04.004

Minor update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/issues/433[#433]: Windows: devon command line sets wrong environment variables (with tilde symbol)
* https://github.com/devonfw/ide/pull/435[#435]: fix variable resolution on bash

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/14?closed=1[milestone 2020.04.004].

=== 2020.04.003

Minor update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/issues/395[#395]: variable from devon.properites unset if value is in double quotes
* https://github.com/devonfw/ide/pull/429[#429]: Added script to create a meta file in the users directory after setup

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/13?closed=1[milestone 2020.04.003].

=== 2020.04.002

Minor update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/issues/418[#418]: Make projects optional
* https://github.com/devonfw/ide/pull/421[#421]: update devon4j to 2020.04.002
* https://github.com/devonfw/ide/issues/413[#413]: Update Eclipse to 2020-03
* https://github.com/devonfw/ide/issues/424[#424]: Strange errors on windows if devon.properties contains mixed line endings
* https://github.com/devonfw/ide/issues/399[#399]: launching of Intellij fails with No such file or directory error.
* https://github.com/devonfw/ide/pull/410[#410]: fix jsonmerge for boolean and null values

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/11?closed=1[milestone 2020.04.002].

== devon4j

The consolidated list of features for this devon4j release is as it follows.

=== 2020.12.001

New release of `devon4j` with pluggable web security (CSRF starter) and `CompletableFuture` support for async REST service client as well as other improvements:

* https://github.com/devonfw/devon4j/issues/283[#283]: Support for CompletableFuture in async service client
* https://github.com/devonfw/devon4j/issues/307[#307]: Fix CSRF protection support
* https://github.com/devonfw/devon4j/issues/287[#287]: spring-boot update to 2.3.3
* https://github.com/devonfw/devon4j/issues/288[#288]: Update jackson to 2.11.2
* https://github.com/devonfw/devon4j/issues/293[#293]: Update owasp-dependency-check plugin version to 5.3.2
* https://github.com/devonfw/devon4j/pull/302[#302]: added guide for project/app structure
* https://github.com/devonfw/devon4j/pull/315[#315]: devon4j documentation correction
* https://github.com/devonfw/devon4j/pull/306[#306]: improve documentation to launch app

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/2020.12.001/devon4j-doc-2020.12.001.pdf[devon4j guide 2020.12.001].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/14?closed=1[milestone devon4j 2020.12.001].

=== 2020.08.001

New release of `devon4j` with async REST service client support and other improvements:

* https://github.com/devonfw/devon4j/issues/279[#279]: support for async service clients
* https://github.com/devonfw/devon4j/issues/277[#277]: Update Security-Guide to recent OWASP Top (2017)
* https://github.com/devonfw/devon4j/pull/281[#281]: cleanup documentation

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/2020.08.001/devon4j-doc-2020.08.001.pdf[devon4j guide 2020.08.001].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/12?closed=1[milestone devon4j 2020.08.001].

=== 2020.04.002

Minor update of `devon4j` with the following bugfixes and small improvements:

* https://github.com/devonfw/devon4j/issues/261[#261]: JUnit4 backward compatibility
* https://github.com/devonfw/devon4j/pull/267[#267]: Fix JWT permission expansion
* https://github.com/devonfw/devon4j/issues/254[#254]: JWT Authentication support for devon4j-kafka
* https://github.com/devonfw/devon4j/issues/258[#258]: archetype is still lacking a .gitignore
* https://github.com/devonfw/devon4j/pull/273[#273]: Update libs
* https://github.com/devonfw/devon4j/pull/271[#271]: Do not enable resource filtering by default
* https://github.com/devonfw/devon4j/issues/255[#255]: Kafka: Support different retry configuration for different topics

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/2020.04.002/devon4j-doc-2020.04.002.pdf[devon4j guide 2020.04.002].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/11?closed=1[milestone devon4j 2020.04.002].

== devon4node

New `devon4node` version is published, the changes are:

On this release we have deprecated devon4node cli, now we use nest cli, and we have added a GraphQL sample.

* https://github.com/devonfw/devon4node/pull/375[#375]: GraphQL Sample.
* https://github.com/devonfw/devon4node/pull/357[#257]: D4N cli remove

== CobiGen

Various bugfixes were made as well as consolidating behavior of eclipse vs maven vs cli by properly sharing more code across the different clients.
Also properly takes into account a files line delimiter instead of defaulting to those of the host system.

https://github.com/devonfw/cobigen/milestone/181?closed=1[CobiGen CLI v7.1.0]
https://github.com/devonfw/cobigen/milestone/172?closed=1[CobiGen Maven Plug-in v7.1.0]
https://github.com/devonfw/cobigen/milestone/170?closed=1[CobiGen Eclipse Plug-in v7.1.0]

=== Templates

* Removed environment.ts from the crud_angular_client_app/CRUD devon4ng Angular App increment since Cobigen did not make any changes in it
* Removed cross referencing between template increments since there is currently no useful use case for it and it leads to a few problems
* https://github.com/devonfw/cobigen/milestone/182?closed=1[v2020.12.001]

=== Java Plug-in
	
* Now properly merges using the input files line delimiters instead of defaulting to those of the host system.
* https://github.com/devonfw/cobigen/milestone/169?closed=1[v7.1.0]

=== TypeScript Plug-in

* Fixed NPE Added the option to read a path from an object input
* https://github.com/devonfw/cobigen/milestone/185?closed=1[v7.1.0]

=== Property Plug-in

* Now properly merges using the input files line delimiters instead of defaulting to those of the host system.
* https://github.com/devonfw/cobigen/milestone/178?closed=1[v7.1.0]

=== OpenAPI Plug-in

* Fixed an issue where nullable enums lead to errors
* https://github.com/devonfw/cobigen/milestone/176?closed=1[7.1.0]

=== Textmerger

* Now properly merges using the input files line delimiters instead of defaulting to those of the host system.
* https://github.com/devonfw/cobigen/milestone/179?closed=1[v7.1.0]
* https://github.com/devonfw/cobigen/milestone/177?closed=1[v7.1.1]

== Sonar devon4j plugin

With this release, we made the package structure configurable and did some other improvements and fixes:

* https://github.com/devonfw/sonar-devon4j-plugin/issues/117[#117]: Rule from checkstyle plugin could not be instantiated in our quality profile
* https://github.com/devonfw/sonar-devon4j-plugin/issues/118[#118]: NPE during project analysis
* https://github.com/devonfw/sonar-devon4j-plugin/issues/97[#97]: Custom configuration for architecture
* https://github.com/devonfw/sonar-devon4j-plugin/issues/92[#92]: Display warnings on the 'devonfw' config page in the 'Administration' section of SonarQube
* https://github.com/devonfw/sonar-devon4j-plugin/issues/95[#95]: Add 3rd Party rule to avoid Immutable annotation from wrong package
* https://github.com/devonfw/sonar-devon4j-plugin/issues/94[#94]: Add 3rd Party rule to avoid legacy date types
* https://github.com/devonfw/sonar-devon4j-plugin/issues/93[#93]: Improve devonfw Java quality profile
* https://github.com/devonfw/sonar-devon4j-plugin/pull/114[#114]: Deleted unused architecture config from SonarQube settings to avoid confusion

Changes for this release can be found in https://github.com/devonfw/sonar-devon4j-plugin/milestone/8?closed=1[milestone 2020.12.001] and 
 https://github.com/devonfw/sonar-devon4j-plugin/milestone/7?closed=1[milestone 2020.12.002]

== devon4net

The consolidated list of features for `devon4net` is as follows:

* LiteDb: - Support for LiteDB - Provided basic repository for CRUD operations.
* RabbitMq: - Use of EasyQNet library to perform CQRS main functions between different microservices - Send commands / Subscribe queues with one C# sentence - Events management: Handled received commands to subscribed messages - Automatic messaging backup when sent and handled (Internal database via LiteDB and database backup via Entity Framework)
* MediatR: - Use of MediatR library to perform CQRS main functions in memory - Send commands / Subscribe queues with one C# sentence - Events management: Handled received commands to subscribed messages - Automatic messaging backup when sent and handled (Internal database via LiteDB and database backup via Entity Framework)
* SmaxHcm: - Component to manage Microfocus SMAX for cloud infrastructure services management
* CyberArk: - Manage safe credentials with CyberArk
* AnsibleTower: - Ansible automates the cloud infrastructure. devon4net integrates with Ansible Tower via API consumption endpoints
* gRPC+Protobuf: - Added Client + Server basic templates sample gRPC with Google's Protobuf protocol using devon4net
* Kafka: - Added Apache Kafka support for deliver/consume messages and create/delete topics as well
* AWS support
	** AWS Template to create serverless applications with auto generation of an APIGateway using AWS base template
	** AWS template to create pure Lambda functions and manage SQS Events, SNS Events, Generic Events, CloudWatch, S3 Management, AWS Secrets management as a configuration provider in .NET life cycle
	** AWS CDK integration component to create/manage AWS infrastructures (Infra As Code): Database, Database cluster, VPC, Secrets, S3 buckets, Roles…
* Minor performance and stability improvements such Entity framework migration integration
* Updated to the latest .net Core 3.1 TLS

== dashboard (beta version)

We are adding dashboard beta version as part of this release. Dashboard is a tool that allows you to create and manage devonfw projects.It makes it easy to onboard a new person with devonfw.

* Dashboard list all ide available on user system or if no ide is availble it will provide option to download latest version of ide.
* Project creation and management: Project page list all projects created by user using dahboard. User will be able to create devon4j, devon4ng and devon4node projects using dashboard. 
* Support for Eclipse and VSCode IDE
* Integrated devonfw-ide usage guide from the website

== Solicitor

Solicitor is a tool which helps managing Open Source Software used within projects. Below is consolidated feature list of solicitor:

* Standalone Command Line Java Tool
* Importers for component/license information from
  * Maven
  * Gradle
  * NPM
  * CSV (e.g. for manual entry of data)
* Rules processing (using Drools Rule Engine) controls the the different phases:
  * Normalizing / Enhancing of license information
  * Handling of multilicensing (including selection of applicable licenses) and re-licensing
  * Legal evaluation
* Rules to be defined as Decision Tables
* Sample Decision Tables included
* Automatic download and file based caching of license texts
  * Allows manual editing / reformatting of license text
* Output processing
  * Template based text (Velocity) and XLS generation
  * SQL based pre-processor (e.g. for filtering, aggregation)
  * Audit log which documents all applied rules for every item might be included in report
  * "Diff Mode" allows to mark data which has changed as compared to a previous run of Solicitor (in Velocity and XLS reporting)
* Customization
  * Project specific configuration (containing e.g. reporting templates, decision tables) allows to override/amend builtin configuration
  * Builtin configuration might be overridden/extended by configuration data contained in a single extension file (ZIP format)
  * This allows to safely provide organization specific rules and reporting templates to all projects of an organization (e.g. to reflect the specific OSS usage policy of the organization) 
  
== MrChecker

MrChecker Test Framework is an end to end test automation framework written in Java. It is an automated testing framework for functional testing of web applications, API web services, Service Virtualization, Security, native mobile apps and, in the near future, databases. All modules have tangible examples of how to build resilient integration test cases based on delivered functions. Below is consolidated list of updates in MrChecker:

* Migration of core module to junit5
* Extension of MrCheckers tests harness
* Migration of mrchecker-example-module to junit 5
* Migration guide https://devonfw.com/website/pages/docs/master-mrchecker.asciidoc_migration-from-junit4-to-junit5.html
* Upgrade to cucumber 6.7.0
* Release of the 3.0.1 version to maven-central

== Trainings/tutorials   

* Katakoda tutorials : https://katacoda.com/devonfw
* Youtube tutorials : https://www.youtube.com/channel/UCtb1p-24jus-QoXy49t9Xzg