:toc: macro
toc::[]


:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing


= devonfw Release notes 2021.04

== Introduction

We are proud to announce the release of devonfw version 2021.04. 

This release includes lots of addition of new features, updates and bug fixes but it is very important to highlight the following improvements:

== devonfw IDE

The consolidated list of features for this devonfw IDE release is as it follows.

=== 2021.04.001

Update with the following bugfixes and improvements:

* https://github.com/devonfw/ide/issues/537[#537]: Update eclipse to 2021-03
* https://github.com/devonfw/ide/issues/287[#287]: Command autocompletion
* https://github.com/devonfw/ide/issues/536[#536]: Improve handling of aborted downloads
* https://github.com/devonfw/ide/issues/542[#542]: Support placeholders in settings.xml template
* https://github.com/devonfw/ide/issues/557[#557]: minimize setup by reducing DEVON_IDE_TOOLS
* https://github.com/devonfw/ide/issues/550[#550]: update maven to 3.8.1
* https://github.com/devonfw/ide/issues/545[#545]: update devon4j to 2021.04.002 and add migration
* https://github.com/devonfw/ide/issues/575[#575]: jasypt support for password encryption and decryption
* https://github.com/devonfw/ide/issues/546[#546]: Problems with tm-terminal Eclipse plugin
* https://github.com/devonfw/ide/issues/553[#553]: VSCode user-data-dir shall be part of workspace config
* https://github.com/devonfw/ide/issues/513[#513]: Configurable generation of IDE start scripts

The full list of changes for this release can be found in https://github.com/devonfw/ide/milestone/18?closed=1[milestone 2021.04.001].

== devon4j

The consolidated list of features for this devon4j release is as it follows.

== 2021.04.002

Bugfix release of with the following stories:
* https://github.com/devonfw/devon4j/issues/389[#389]: archetype build broken with ci-friendly-maven
* https://github.com/devonfw/devon4j/pull/391[#391]: jasypt documentation improvements
* https://github.com/devonfw/devon4j/pull/387[#387]: rebuild and updated diagram with drawio

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/2021.04.002/devon4j-doc-2021.04.002.pdf[devon4j guide 2021.04.002].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/18?closed=1[milestone devon4j 2020.04.002].

=== 2021.04.001

New release of `devon4j` with fixes, updates and improvements:

* https://github.com/devonfw/devon4j/issues/370[#370]: Minor updates (spring-boot 2.4.4, jackson 2.12.2, CXF 3.4.3, etc.) 
* https://github.com/devonfw/devon4j/issues/366[#366]: BaseTest.isInitialSetup() broken
* https://github.com/devonfw/devon4j/issues/85[#85]: ci-friendly-maven also for archetype
* https://github.com/devonfw/devon4j/issues/373[#373]: CORS starter not part of devon4j release
* https://github.com/devonfw/devon4j/issues/164[#164]: Flattened pom for core project invalid
* https://github.com/devonfw/devon4j/issues/323[#323]: Add spring integration test to archetype
* https://github.com/devonfw/devon4j/pull/351[#351]: improved error handling of service client
* https://github.com/devonfw/devon4j/issues/71[#71]: improve documentation for strong password encryption
* https://github.com/devonfw/devon4j/issues/354[#354]: JMS senders should not be part of data access layer, but logical layer
* https://github.com/devonfw/devon4j/pull/337[#377]: updated T-Architecture
* https://github.com/devonfw/devon4j/issues/294[#294]: integrate sonarcloud analysis into devon4j CI pipeline

Documentation is available at https://repo.maven.apache.org/maven2/com/devonfw/java/doc/devon4j-doc/2021.04.001/devon4j-doc-2021.04.001.pdf[devon4j guide 2021.04.001].
The full list of changes for this release can be found in https://github.com/devonfw/devon4j/milestone/15?closed=1[milestone devon4j 2020.04.001].

== devon4ng

Updated template and samples to Angular 11.
Updated guide of devon4ng.

== MrChecker

MrChecker Test Framework is an end to end test automation framework written in Java. It is an automated testing framework for functional testing of web applications, API web services, Service Virtualization, Security, native mobile apps and, in the near future, databases. All modules have tangible examples of how to build resilient integration test cases based on delivered functions. Two new modules are added to MrChecker:

* DB Module - we have created a module intended to make testing efforts on DBs easier. It is founded on JPA in conjunction with Hibernate and therefore supports both high level, object based access to DB entities via the IDao interface and low level, native SQL commands via the EntityManager class .

* CLI Module - we have created a module intended to make testing command line applications like compilers or batches easier and faster. Huge success here is that, team using this solution was able to prepare a test suite, without app provided, basing only on documentation and using mocking technique.

== Trainings/tutorials   

* Katakoda tutorials : https://katacoda.com/devonfw
* Youtube tutorials : https://www.youtube.com/channel/UCtb1p-24jus-QoXy49t9Xzg