name: Update Website
on: pull_request_target
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Website on success
        run: |
          git clone https://${BUILD_USER}:${BUILD_USER_PASSWD}@github.com/${ORG}/devonfw.github.io.git --recurse-submodules
          cd devonfw.github.io/devonfw-guide
          git checkout master
          git pull
          cd ..
          git checkout develop
          git add devonfw-guide
          git commit -m "[DocUpdate]"
          git push origin develop
